config/routes.rb
FacebookLite::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    member do
      get "wall"
      get "photos"
      get "about"
      get "friends"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  root :to => 'home_pages#root'
  get "/friend-requests", to: 'home_pages#friend_req'
  get "/notifications", to: 'home_pages#notifications'


  resources :posts, only: [:create, :update, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :friendships, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :messages, only: [:create, :index, :show]
  resources :photos, only: [:show, :update] do
    resources :profile_pictures, only: [:create]
  end
  
  resources :notifications, only: [:destroy]
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :college, :current_city, :employer, :high_school, :hometown, :user_id, :interests
  validates_presence_of :high_school

  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :require_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(params[:profile])
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to root_url
    else
      flash[:errors] = @profile.errors.full_messages
      render :new
    end
  end

  def edit
    @profile = Profile.find_by_user_id(current_user.id)
  end

  def update
    @profile = Profile.find_by_user_id(current_user.id)
    @profile.update_attributes(params[:profile])
    redirect_to root_url
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<form action="<%= url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= value %>">

  <label for="high_school" class="profile-label">High School</label>
  <input type="text" name="profile[high_school]" value="<%= @profile.high_school %>" id="high_school" class="profile-input">

  <label for="college" class="profile-label">College / University</label>
  <input type="text" name="profile[college]" value="<%= @profile.college %>" id="college" class="profile-input">

  <label for="employer" class="profile-label">Employer</label>
  <input type="text" name="profile[employer]" value="<%= @profile.employer %>" id="employer" class="profile-input">

  <label for="current_city" class="profile-label">Current City</label>
  <input type="text" name="profile[current_city]" value="<%= @profile.current_city %>" id="current_city" class="profile-input">

  <label for="hometown" class="profile-label">Hometown</label>
  <input type="text" name="profile[hometown]" value="<%= @profile.hometown %>" id="hometown" class="profile-input">

  <label for="interests" class="profile-label">Interests</label>
  <input type="text" name="profile[interests]" value="<%= @profile.interests %>" id="interests" class="profile-input">

  <p><input type="submit" value="Submit Your Profile"></p>
</form>

app/views/profiles/edit.html.erb
<div class="profile-setup-page">
  <section class="profile-form">
    <h2 class="profile-header">Edit Your Basic Information</h2>

    <%= render :partial => 'form', :locals => { url: profile_url(@profile), value: "put"  } %>
  </section>
</div>

app/views/profiles/new.html.erb
<div class="profile-setup-page">
  <section class="profile-form">
    <h3 class="profile-header">Fill Out Your Basic Information</h2>

    <%= render :partial => 'form', :locals => { url: profiles_url, value: "post"} %>
  </section>
</div>