config/routes.rb
FacebookLite::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    member do
      get "wall"
      get "photos"
      get "about"
      get "friends"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  root :to => 'home_pages#root'
  get "/friend-requests", to: 'home_pages#friend_req'
  get "/notifications", to: 'home_pages#notifications'


  resources :posts, only: [:create, :update, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :friendships, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :messages, only: [:create, :index, :show]
  resources :photos, only: [:show, :update] do
    resources :profile_pictures, only: [:create]
  end
  
  resources :notifications, only: [:destroy]
end

app/models/user.rb
require "bcrypt"

class User < ActiveRecord::Base
  attr_accessible :email, :password, :first_name, :last_name, :birth_month, :birth_day, :birth_year, :gender
  attr_reader :password
  validates :password_digest, presence: { :message => "Password can't be blank" }
  validates :password, length: { minimum: 6 }
  validates_presence_of :email, :session_token, :first_name, :last_name, :birth_month, :birth_day, :birth_year, :gender
  validates_uniqueness_of :email

  before_validation :reset_session_token!, on: :create

  has_one(
    :profile,
    class_name: 'Profile',
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :sender_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :received_posts,
    class_name: "Post",
    foreign_key: :receiver_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :messages,
    class_name: "Message",
    foreign_key: :sender_id,
    primary_key: :receiver_id,
    dependent: :destroy
  )

  has_many(
    :received_messages,
    class_name: "Message",
    foreign_key: :receiver_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :initiated_friendships,
    class_name: "Friendship",
    foreign_key: :friender_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :received_friendships,
    class_name: "Friendship",
    foreign_key: :friendee_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :photos,
    class_name: "Photo",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :notifications,
    class_name: "Notification",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :sent_notifications,
    class_name: "Notification",
    foreign_key: :sender_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  has_one(
    :profile_picture,
    class_name: "ProfilePicture",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many :received_friends, through: :received_friendships, source: :friender
  has_many :initiated_friends, through: :initiated_friendships, source: :friendee
  has_one :profile_pic, through: :profile_picture, source: :photo

  def friends
    friends = []
    self.received_friends.each do |friend|
      friends << friend unless friend.initiated_friendships.where(is_pending: false, friendee_id: self.id).empty?
    end


    self.initiated_friends.each do |friend|
      friends << friend unless friend.received_friendships.where(is_pending: false, friender_id: self.id).empty?
    end

    friends
  end

  def friends_ids
    friend_ids = [self.id]
    self.friends.each do |friend|
      friend_ids << friend.id
    end

    friend_ids
  end

  def pending_received_friends
    pending_friends = []
    self.pending_received_friend_requests.each do |friendship|
      pending_friends << User.find(friendship.friender_id)
    end

    pending_friends
  end

  def user_requests
    self.initiated_friendships.where(is_pending: false) + self.received_friendships.where(is_pending: false)
  end

  def pending_initiated_friend_requests
    self.initiated_friendships.where(is_pending: true)
  end

  def pending_received_friend_requests
    self.received_friendships.where(is_pending: true)
  end


  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_current_user!, only: :new
  before_filter :require_user!, except: [:new, :create]

  def index
    @users = User.includes(:profile_pic).all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      log_in(@user)
      redirect_to new_profile_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def wall
    @user = User.find(params[:id])
  end

  def photos
    @user = User.find(params[:id])
  end

  def about
    @user = User.find(params[:id])
  end

  def friends
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.erb
<% current_user_requests = current_user.user_requests %>
<% users_pending_initiated_friend_requests = current_user.pending_initiated_friend_requests %>
<% users_pending_received_friend_requests = current_user.pending_received_friend_requests %>

<% received_friendship = users_pending_received_friend_requests.select { |friendship| friendship.friender_id == @user.id }.first %>
		<% initiated_friendship = users_pending_initiated_friend_requests.select { |friendship| friendship.friendee_id == @user.id }.first %>
		<% valid_friendship = current_user_requests.select { |friendship| friendship.friendee_id == @user.id || friendship.friender_id == @user.id }.first %>

<section class="wall-header">
  <div class="wall-header-body group">
    <% temp_profile_url = @user.profile_pic ? @user.profile_pic.pic : "default_profile_pic.jpeg" %>
    <%= image_tag(temp_profile_url, class: "wall-photo") %>

    <div class="wall-header-right">
      <h3><%= @user.first_name + " " + @user.last_name %></h3>
      <h5 class="friendship-button">
				<% if @user == current_user %>
					<%= link_to "Edit Profile", edit_profile_url(@user) %>
				<% else %>
	        <%= render "layouts/friendship_buttons", user: @user, valid_friendship: valid_friendship, received_friendship: received_friendship, initiated_friendship: initiated_friendship %>
				<% end %>
      </h5>
    </div>
  </div>

  <nav class="wall-nav group">
    <ul>
      <li><%= link_to "Wall", wall_user_url(@user.id) %></li>
      <li><%= link_to "Photos", photos_user_url(@user.id) %></li>
      <li><%= link_to "About", about_user_url(@user.id) %></li>
      <li><%= link_to "Friends", friends_user_url(@user.id) %></li>
    </ul>
  </nav>
</section>

app/views/users/_optional_row.html.erb
<% unless detail == "" %>
  <tr>
    <th><%= title %></th>
    <td><%= detail %></td>
  </tr>
<% end %>

app/views/users/about.html.erb
<%= render "header" %>

<section class="about">
  <header>
    <h3 class="about-title">About</h3>
  </header>

  <article>
    <div class="right">
      <h2 class="table-header">Basic Information</h2>
      <table class="basic-info" cellpadding="5">
        <tr>
          <th>Birthday</th>
          <td><%= "#{@user.birth_month} #{@user.birth_day}, #{@user.birth_year}" %><td>
        </tr>

        <tr>
          <th>Gender</th>
          <td><%= @user.gender %></td>
        </tr>

        <%= render "optional_row", detail: @user.profile.current_city, title: "Current City" %>

        <%= render "optional_row", detail: @user.profile.hometown, title: "Hometown" %>

        <%= render "optional_row", detail: @user.profile.interests, title: "Interests" %>
      </table>


    </div>


    <div class="left">
      <h2 class="table-header">Work and Education</h2>

      <table class="work-info" cellpadding="5">
        <%= render "optional_row", detail: @user.profile.high_school, title: "High School" %>

        <%= render "optional_row", detail: @user.profile.college, title: "College/University" %>

        <%= render "optional_row", detail: @user.profile.employer, title: "Employer" %>

      </table>
    </div>

  </article>

</section>

app/views/users/friends.html.erb
<%= render "header" %>

<section class="friends">
  <header>
    <h3>Friends</h3>
  </header>
	
	<article>
		<ul>
			<% friends = User.includes(:profile_pic).where("id IN (?)", current_user.friends_ids) %>
			
			<% friends.each do |friend| %>
			
			<li class="user-index">
        <% temp_profile_url = friend.profile_pic ? friend.profile_pic.pic : "default_profile_pic.jpeg" %>
        <%= link_to image_tag(temp_profile_url, class: "user-header-photo"), wall_user_url(friend) %>
				
				<div class="index-right">
					<%= link_to "#{friend.first_name} #{friend.last_name}", wall_user_url(friend) %>
					
					<div class="friendship-button">
						<input type="button" value="&#10004 Friends" class="is-friend"> 
					</div>
				</div>
			</li>
			
			<% end %>
		</ul>
		
		
	</article>
		
</section>

app/views/users/index.html.erb
<% current_user_requests = current_user.user_requests %>
<% users_pending_initiated_friend_requests = current_user.pending_initiated_friend_requests %>
<% users_pending_received_friend_requests = current_user.pending_received_friend_requests %>

<section class="users-index">
  <% @users.each do |user| %>
      <% next if user.id == current_user.id %>

      <article class="user-index">

  		<% received_friendship = users_pending_received_friend_requests.select { |friendship| friendship.friender_id == user.id }.first %>
  		<% initiated_friendship = users_pending_initiated_friend_requests.select { |friendship| friendship.friendee_id == user.id }.first %>
  		<% valid_friendship = current_user_requests.select { |friendship| friendship.friendee_id == user.id || friendship.friender_id == user.id }.first %>

      <% temp_profile_url = user.profile_pic ? user.profile_pic.pic : "default_profile_pic.jpeg" %>
      <%= link_to image_tag(temp_profile_url, class: "user-header-photo"), wall_user_url(user) %>


      <div class="index-right">
        <%= link_to "#{user.first_name} #{user.last_name}", wall_user_url(user) %>

				<div class="friendship-button">
				<%= render "layouts/friendship_buttons", user: user, valid_friendship: valid_friendship, received_friendship: received_friendship, initiated_friendship: initiated_friendship %>
    		</div>
				
      </div>
			
    </article>
  <% end %>
</section>

<script>
$(document).ready(function(event){
	$(".index-right").on("ajax:success", ".unfriend-button", function(event, data){
		$button = $(this);
		
		$div = $button.closest(".friendship-button");
		$div.empty();
		$div.append(data);
	});
	
	$(".index-right").on("ajax:success", ".accept-friend-form", function(event, data){
		$form = $(this);
		
		$div = $form.closest(".friendship-button");
		$div.empty();
		$div.append(data);
	});
	
	$(".index-right").on("ajax:success", ".friend-form", function(event, data){
		$form = $(this);
		
		$div = $form.closest(".friendship-button");
		$div.empty();
		$div.append(data);
	});
});
</script>

app/views/users/new.html.erb
<div class="sign-up-page">
	<h2 class="sign-up-header">Create Your Fakebook Account</h2>
	
  <section class="sign-up">
    <form action="<%= users_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="sign-up-buttons">
				<input type="text" name="user[first_name]" value="<%= @user.first_name %>" class="sign-up-input" placeholder="First Name">

	      <input type="text" name="user[last_name]" value="<%= @user.last_name %>" class="sign-up-input" placeholder="Last Name">

	      <input type="text" name="user[email]" value="<%= @user.email %>" class="sign-up-input" placeholder="Email">

	      <input type="password" name="user[password]" class="sign-up-input" placeholder="Password">

	      <div class="birth-date">
	        <div class="birth-date-header">Birthday</div>
	        <select name="user[birth_month]" id="user_birth_month">
	          <option selected="selected" value="">Month</option>
	          <% months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] %>
	          <% months.each do |month| %>
	            <option value="<%= month %>"><%= month %></option>
	          <% end %>
	        </select>

	        <select name="user[birth_day]" id="user_birth_day">
	          <option selected="selected" value="">Day</option>
	          <% (1..30).each do |day| %>
	            <option value="<%= day %>"><%= day %></option>
	          <% end %>
	        </select>

	        <select name="user[birth_year]" id="user_birth_year">
	          <option selected="selected" value="">Year</option>
	          <% (1950..DateTime.now.year).to_a.reverse.each do |year| %>
	            <option value="<%= year %>"><%= year %></option>
	          <% end %>
	        </select>
	      </div>

	      <div class="gender">
					<div class="gender-type">
		        <label for="male">Male</label>
		        <input type="radio" name="user[gender]" value="Male" id="male">
					</div>
					
					<div class="gender-type">
		        <label for="female">Female</label>
		        <input type="radio" name="user[gender]" value="Female" id="male">
					</div>
	      </div>


	      <input type="submit" value="Sign Up" class="sign-in-submit">
			</div>
    </form>
  </section>
	
	<div class="sign-in-button-wrapper">
	  <%= button_to "Sign In to an existing Account", new_session_url, method: :get, class: "sign-in-button" %>
	</div>
</div>

app/views/users/photos.html.erb
<%= render "header" %>

<section class="photos">
  <header>
    <h3>Photos</h3>
  </header>

  <article>
    <ul class="user-photos">
      <% @user.photos.each do |photo| %>
      <li>
        <%= image_tag(photo.pic, class: "photo-index-view") %>
      </li>
      <% end %>
    </ul>
  </article>
</section>

app/views/users/wall.html.erb
<%= render "header" %>

<div class="wall-wrapper">
  <div class="wall-sidebar">
    <section class="brief-about">
      <header class="about-header">About</header>

      <article>
        <ul class="about-list">
          <% user_college = @user.profile.college %>
          <li>
            Studied at <%= user_college == "" ? @user.profile.high_school : user_college %>
          </li>

          <li>
            Birthday is <%= "#{@user.birth_month} #{@user.birth_day}, #{@user.birth_year}" %>
          </li>

          <li>
            Its a <%= @user.gender == "Male" ? "He" : "She" %>
          </li>
        </ul>

      </article>
    </section>

    <section class="brief-photos">
      <header class="photo-header">Photos</header>

      <ul class="brief-photo-list group">
        <% if @user.photos.count >= 4 %>
          <% @user.photos.sample(4).each do |photo| %>
            <li><%= image_tag(photo.pic, class: "brief-photo") %></li>
          <% end %>
        <% elsif @user.photos.count > 0 %>
          <% 4.times do |t| %>
            <li><%= image_tag(@user.photos.sample(1)[0].pic, class: "brief-photo") %></li>
          <% end %>
        <% else %>
          <% 4.times do |t| %>
            <li><%= image_tag("default_profile_pic.jpeg", class: "brief-photo") %></li>
          <% end %>
        <% end %>
      </ul>
    </section>
  </div>

  <div class="wall-right">
    <section class="wall-update-status">
      <% if @user.id == current_user.id %>
        <h5>Update Status</h5>
        <%= render "layouts/new_status" %>
      <% elsif current_user.friends_ids.include?(@user.id) %>
        <h5>Post</h5>
        <%= render "layouts/new_post", user: @user %>
      <% end %>
    </section>

    <section class="main-wall">
      <article>
        <ul class="posts-list">
          <% @user.received_posts.includes(:photos, :receiver, sender: :profile_pic, :comments => [:user => [:profile_pic]]).order('created_at DESC').each do |post| %>
            <li>
              <%= render "layouts/post_view", post: post, show_page: false %>
            </li>
          <% end %>
        </ul>
      </article>
    </section>
  </div>
</div>

<script>
$(document).ready(function(event){
  $("#update-status-form").on("ajax:success", function(event, data){
    var $form = $(this);
    $(".posts-list").prepend(data);

    $form[0].reset();
  });
	
  $("#new-post-form").on("ajax:success", function(event, data){
    var $form = $(this);
    $(".posts-list").prepend(data);

    $form[0].reset();
  });

  $(".posts-list").on("ajax:success", ".delete-post-button", function(event, data){
    var $button = $(this);
    var $post = $button.closest(".post-wrapper");

    $post.remove();
  });

  $(".posts-list").on("ajax:success", "#like-form", function(event, data){
    var $form = $(this);
    var $ul = $form.closest(".edit-post");
    $ul.find(".like-button-posts").remove();

    $ul.append(data);
  });

  $(".posts-list").on("ajax:success", ".delete-like-button", function(event, data){
    var $button = $(this);
    var $ul = $button.closest(".edit-post");
    $ul.find(".like-button-posts").remove();

    $ul.append(data);
  });

  $(".posts-list").on("ajax:success", "#new-comment-form", function(event, data){
    var $form = $(this);
    var $ul = $form.closest(".everything-right");
    var $ul2 = $ul.find(".comments-list")

    $ul2.append(data);

    $form[0].reset();
  });

  $(".posts-list").on("ajax:success", ".delete-comment-button", function(event, data){
    var $button = $(this);
    var $comment = $button.closest(".list-comment");

    $comment.remove();
  });
	
	$(".wall-header-right").on("ajax:success", ".unfriend-button", function(event, data){
		$button = $(this);
		
		$div = $button.closest(".friendship-button");
		$div.empty();
		$div.append(data);
	});
	
	$(".wall-header-right").on("ajax:success", ".accept-friend-form", function(event, data){
		$form = $(this);
		
		$div = $form.closest(".friendship-button");
		$div.empty();
		$div.append(data);
	});
	
	$(".wall-header-right").on("ajax:success", ".friend-form", function(event, data){
		$form = $(this);
		
		$div = $form.closest(".friendship-button");
		$div.empty();
		$div.append(data);
	});
});
</script>