config/routes.rb
FacebookLite::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    member do
      get "wall"
      get "photos"
      get "about"
      get "friends"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  root :to => 'home_pages#root'
  get "/friend-requests", to: 'home_pages#friend_req'
  get "/notifications", to: 'home_pages#notifications'


  resources :posts, only: [:create, :update, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :friendships, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :messages, only: [:create, :index, :show]
  resources :photos, only: [:show, :update] do
    resources :profile_pictures, only: [:create]
  end
  
  resources :notifications, only: [:destroy]
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  before_filter :require_user!

  def root
    @news = Post.includes(:photos, :receiver, sender: :profile_pic, :comments => [:user => [:profile_pic]]).order('created_at DESC').limit(10).select { |post| current_user.friends_ids.include?(post.receiver_id) || current_user.friends_ids.include?(post.sender_id) }

    render :root
  end

  def friend_req
  end

  def notifications
    @notifications = Notification.includes(:notifiable, :sender => [:profile_pic]).where(user_id: current_user.id)
  end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/friend_req.html.erb
<div class="pending-header-wrapper">
  <h1 class="pending-request-header">Pending Friend Requests</h1>
</div>

<section class="users-index">
  <% if current_user.pending_received_friends.empty? %>
    <p class="no-requests">You Have No Pending Requests</p>
  <% else %>
		<% current_user.pending_received_friends.each do |friend| %>
  		<article class="user-index">
        <% temp_profile_url = friend.profile_pic ? friend.profile_pic.pic : "default_profile_pic.jpeg" %>
        <%= link_to image_tag(temp_profile_url, class: "user-header-photo"), wall_user_url(friend) %>

  		  <% received_friendship = Friendship.where(friender_id: current_user.id, friendee_id: friend.id) %>

        <div class="index-right">
          <%= link_to "#{friend.first_name} #{friend.last_name}",	 wall_user_url(friend) %>
  				
					<div class="friendship-button">
						<%= render "layouts/accept_friend", user: friend, url: friendship_url(received_friendship) %>
						<%= button_to "Cancel Friend Request", friendship_url(received_friendship), method: :delete, :remote => true, :form_class => "unfriend-button" %>
					</div>
        </div>
      </article>
		<% end %>
  <% end %>
</section>

<script>
$(document).ready(function(event){
	$(".index-right").on("ajax:success", ".unfriend-button", function(event, data){
		$button = $(this);
		
		$article = $button.closest(".user-index");
		$article.remove();
	});
	
	$(".index-right").on("ajax:success", ".accept-friend-form", function(event, data){
		$form = $(this);
		
		$article = $form.closest(".user-index");
		$article.remove();
	});
});
</script>

app/views/home_pages/notifications.html.erb
<div class="notification-page">
  <h1>Recent Notifications</h1>

		<% @notifications.reverse.each do |notification| %>
		<% notifiable_type = notification.notifiable_type %>
    <% sender = notification.sender %>

		<section class="notification">
      <% temp_profile_url = sender.profile_pic ? sender.profile_pic.pic : "default_profile_pic.jpeg" %>

      <div class="notification-image">
        <%= link_to image_tag(temp_profile_url, class: "notification-photo"), wall_user_url(sender) %>
      </div>

      <div class="notification-right">
        <div class="delete-notification">
          <%= button_to "Delete Notification", notification_url(notification), method: :delete, class: "delete-not-button", :remote => true, :form_class => "delete-notification-button" %>
        </div>

        <div class="notification-body">
      		<%= link_to "#{sender.first_name} #{sender.last_name}", wall_user_url(sender) %>

    			<% if notifiable_type == "Post" %>
    				has sent you a
    				<%= link_to "post", wall_user_url(current_user) %>
    			<% elsif notifiable_type == "Message" %>
    				has sent you a
    				<%= link_to "message", message_url(notification.notifiable_id) %>
    			<% elsif notifiable_type == "Friendship" %>
    				<% if notification.notifiable.is_pending == true %>
    					has sent you a <%= link_to "friend request", "/friend-requests" %>
    				<% elsif notification.notifiable.friendee_id != current_user.id %>
    					has confirmed your <b>friend request</b>
            <% else %>
              and you are now <b>friends</b>
    				<% end %>
    			<% elsif notifiable_type == "Comment" %>
    				has commented on your
    				<%= link_to "post", wall_user_url(notification.notifiable.post.receiver_id) %>
    			<% elsif notifiable_type == "Like" %>
    				<% liked_obj = notification.notifiable.likeable %>
    				<% if liked_obj.class.name == "Comment" %>
    					<% if liked_obj.post.receiver.id == current_user.id %>
    						likes your comment on
    						<%= link_to "your wall", wall_user_url(liked_obj.post.receiver) %>
    					<% else %>
    						likes your comment on
    						<%= link_to "#{liked_obj.post.receiver.first_name}'s wall", wall_user_url(liked_obj.post.receiver) %>
    					<% end %>
    				<% elsif liked_obj.class.name == "Post" %>
    					<% if liked_obj.receiver_id == current_user.id %>
    						likes a post on
    						<%= link_to "your wall", wall_user_url(liked_obj.receiver) %>
    					<% else %>
    						likes your post on
    						<%= link_to "#{liked_obj.receiver.first_name}'s wall", wall_user_url(liked_obj.receiver) %>
    					<% end %>
    				<% end %>
      		<% end %>
        </div>
      </div>
    </section>

	<% end %>
</div>


<script>
$(document).ready(function(event){
	$(".notification-page").on("ajax:success", ".delete-notification-button", function(event, data){
		$button = $(this);
		$notification = $button.closest(".notification");
		$notification.remove();
	});
});


</script>

app/views/home_pages/root.html.erb
<div class="body-wrapper">
  <section class="sidebar">

    <header class="sidebar-header">
      <h2><%= current_user.first_name + " " + current_user.last_name %></h5>
      <h5><%= link_to "Edit Profile", edit_profile_url(current_user.profile.id) %></h5>
    </header>

    <div class="favorites">
      <ul class="sidebar-list">
        <li><%= link_to "News Feed", root_url %></li>
        <li><%= link_to "Messages", messages_url %></li>
        <li><%= link_to "Photo", photos_user_url(current_user) %></li>
        <li><%= link_to "List of Users", users_url %></li>
      </ul>
    </div>
  </section>


  <section class="main">
    <header class="update-status">
      <h5>Update Status</h5>
      <%= render "layouts/new_status" %>
    </header>


    <article class="newsfeed">
      <h1>News Feed</h1>

      <ul id="posts-list">
        <% if @news.empty? %>
          <div class="empty-block">GET SOME FRIENDS, YOUR MAKING ME LOOK BAD</div>
        <% else %>
          <% @news.each do |post| %>
            <li class="single-post">
              <%= render "layouts/post_view", post: post, show_page: false %>
            </li>
          <% end %>
        <% end %>
      </ul>

    </article>
  </section>
</div>

<script>
$(document).ready(function(event){
  $("#update-status-form").on("ajax:success", function(event, data){
    var $form = $(this);
    $("#posts-list").prepend(data);

    $form[0].reset();
  });

  $("#posts-list").on("ajax:success", ".delete-post-button", function(event, data){
    var $button = $(this);
    var $post = $button.closest(".post-wrapper");

    $post.remove();
  });

  $("#posts-list").on("ajax:success", "#like-form", function(event, data){
    var $form = $(this);
    var $ul = $form.closest(".edit-post");
    $ul.find(".like-button-posts").remove();

    $ul.append(data);
  });

  $("#posts-list").on("ajax:success", ".delete-like-button", function(event, data){
    var $button = $(this);
    var $ul = $button.closest(".edit-post");
    $ul.find(".like-button-posts").remove();

    $ul.append(data);
  });

  $("#posts-list").on("ajax:success", "#new-comment-form", function(event, data){
    var $form = $(this);
    var $ul = $form.closest(".everything-right");
    var $ul2 = $ul.find(".comments-list")

    $ul2.append(data);

    $form[0].reset();
  });

  $("#posts-list").on("ajax:success", ".delete-comment-button", function(event, data){
    var $button = $(this);
    var $comment = $button.closest(".list-comment");

    $comment.remove();
  });
});
</script>