config/routes.rb
FacebookLite::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    member do
      get "wall"
      get "photos"
      get "about"
      get "friends"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  root :to => 'home_pages#root'
  get "/friend-requests", to: 'home_pages#friend_req'
  get "/notifications", to: 'home_pages#notifications'


  resources :posts, only: [:create, :update, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :friendships, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :messages, only: [:create, :index, :show]
  resources :photos, only: [:show, :update] do
    resources :profile_pictures, only: [:create]
  end
  
  resources :notifications, only: [:destroy]
end

app/views/layouts/_accept_friend.html.erb
<form action="<%= url %>" method="post" data-remote="true" class="accept-friend-form">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">

  <input type="hidden" name="friendship[friendee_id]" value="<%= current_user.id %>">
  <input type="hidden" name="friendship[friender_id]" value="<%= user.id %>">
  <input type="submit" value="Confirm Friend Request">
</form>

app/views/layouts/_comment.html.erb
<form action="<%= post_comments_url(post) %>" method="post" data-remote="true" id="new-comment-form">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="comment[body]" placeholder="Comment..." class="comment-text">

  <p><input type="submit" value="Comment" class="comment-submit"></p>
</form>

app/views/layouts/_comment_view.html.erb
<li class="list-comment group">
  <% commenter = comment.user %>
  <div class="left-comment">
    <% temp_profile_url = commenter.profile_pic ? commenter.profile_pic.pic : "default_profile_pic.jpeg" %>
    <%= link_to image_tag(temp_profile_url, class: "comment-header-photo"), wall_user_url(commenter) %>
	</div>

  <div class="right-comment">
		<%= link_to "#{commenter.first_name} #{commenter.last_name}", wall_user_url(commenter) %>

		<div class="comment-body">
			<%= comment.body %>
		</div>

		<ul class="edit-post group">
			<li>
				<time>
					Commented <%= time_ago_in_words(comment.created_at) %> ago
				</time>
			</li>

			<li>
				<% if commenter.id == current_user.id %>
          <%= button_to "Delete Comment", comment_url(comment), method: :delete, :remote => true, :form_class => "delete-comment-button" %>
        <% end %>
			</li>

			<%= render "layouts/like_button_post", post: comment %>
		</ul>
	</div>
</li>

app/views/layouts/_delete_friendship.html.erb
<%= button_to label, friendship_url(friendship), method: :delete, :remote => true, :form_class => "unfriend-button" %>

app/views/layouts/_friend.html.erb
<form action="<%= friendships_url %>" method="post" data-remote="true" class="friend-form">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="friendship[friendee_id]" value="<%= user.id %>">
  <input type="hidden" name="friendship[friender_id]" value="<%= current_user.id %>">
  <input type="submit" value="Friend">
</form>

app/views/layouts/_friendship_buttons.html.erb
<% if valid_friendship %>
	<%= button_to "Unfriend", friendship_url(valid_friendship), method: :delete, :remote => true, :form_class => "unfriend-button" %>
<% elsif received_friendship %>
	<%= render "layouts/accept_friend", user: user, url: friendship_url(received_friendship) %>
	<%= button_to "Cancel Friend Request", friendship_url(received_friendship), method: :delete, :remote => true, :form_class => "unfriend-button" %>
<% elsif initiated_friendship %>
	<%= button_to "Cancel Request", friendship_url(initiated_friendship), method: :delete, :remote => true, :form_class => "unfriend-button" %>
<% else %>
	<%= render "layouts/friend", user: user %>
<% end %>

app/views/layouts/_like_button_comment.html.erb
<% like = comment.likes.where(user_id: current_user.id) %>

<% if like.empty? %>
  <%= render "layouts/like_comment", comment: comment %>
<% else %>
  <%= button_to "Unlike", like_url(like[0]), method: :delete %>
<% end %>

app/views/layouts/_like_button_post.html.erb
<li class="like-post-list like-button-posts">
  <% like = post.likes.where(user_id: current_user.id) %>
  <% if like.empty? %>
    <%= render "layouts/like_post", post: post, likeable_type: post.class.name %>
  <% else %>
    <%= button_to "Unlike", like_url(like[0]), method: :delete, :remote => true, :form_class => "delete-like-button" %>
  <% end %>
</li>

<li class="like-button-posts">
  <% if post.likes.count > 0 %>
		<span>
      <%= pluralize(post.likes.count, "Like") %>
		</span>
  <% end %>
</li>

app/views/layouts/_like_comment.html.erb
<form action="<%= likes_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="like[likeable_id]" value="<%= comment.id %>">
  <input type="hidden" name="like[likeable_type]" value="Comment">
  <input type="hidden" name="like[user_id]" value="<%= current_user.id %>">
  <p><input type="submit" value="Like"></p>
</form>

app/views/layouts/_like_post.html.erb
<form action="<%= likes_url %>" method="post" data-remote="true" id="like-form">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="like[likeable_id]" value="<%= post.id %>">
  <input type="hidden" name="like[likeable_type]" value="<%= likeable_type %>">
  <input type="hidden" name="like[user_id]" value="<%= current_user.id %>">
  <p><input type="submit" value="Like" class="like"></p>
</form>

app/views/layouts/_new_post.html.erb
<form action="<%= posts_url %>" method="post" data-remote="true" id="new-post-form">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="post[body]" placeholder="Post on Wall..">
  <input type="hidden" name="post[receiver_id]" value="<%= user.id %>">
  <p><input type="submit" value="Post"></p>
</form>

app/views/layouts/_new_status.html.erb
<form action="<%= posts_url %>" method="post" enctype="multipart/form-data" data-remote="true" id="update-status-form">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="post[body]" placeholder="New Status..">
  <input type="hidden" name="post[receiver_id]" value="<%= current_user.id %>">

  <input type="file" name="photo[pic]">

  <p><input type="submit" value="Post" class="submit-button"></p>
</form>

app/views/layouts/_post_view.html.erb
<div class="post-wrapper group">
  <div class="header-photo">
    <% sender = post.sender %>
    <% temp_profile_url = sender.profile_pic ? sender.profile_pic.pic : "default_profile_pic.jpeg" %>
    <%= link_to image_tag(temp_profile_url, class: "post-header-photo"), wall_user_url(sender) %>
  </div>

  <div class="everything-right">
    <div class="post-content group">
      <div class="post-header">
          <% unless post.sender_id == post.receiver_id %>
            <%= link_to "#{sender.first_name} #{sender.last_name}", wall_user_url(sender) %>
            &rarr;
          <% end %>

          <% receiver = post.receiver %>
          <%= link_to "#{receiver.first_name} #{receiver.last_name}", wall_user_url(receiver) %>
      </div>

      <div class="post-body">
        <%= post.body %>
      </div>
    </div>

    <div class="post-body-photo">
      <% photo = post.photos.first %>

      <% if photo %>
        <%= link_to image_tag(photo.pic, class: "post-photo"), photo_url(photo) %>
      <% end %>
    </div>

    <ul class="edit-post group">
			<li>
				<time>
					Posted <%= time_ago_in_words(post.created_at) %> ago
				</time>
			</li>
			
			<li>
				<% if post.sender.id == current_user.id && photo && show_page %>
				  <% if !current_user.profile_pic || photo.id != current_user.profile_pic.id %>
				    <%= button_to "Set this as Profile Pic", photo_profile_pictures_url(photo.id), method: :post %>
				  <% end %>
				<% end %>
			</li>
			
			<li>
        <% if sender.id == current_user.id %>
          <%= button_to "Delete Post", post_url(post), method: :delete, :remote => true, :form_class => "delete-post-button" %>
        <% end %>
			</li>

      <%= render "layouts/like_button_post", post: post %>
    </ul>

    <div class="post-comments">
      <ul class="comments-list">
        <% post.comments.each do |comment| %>
          <%= render "layouts/comment_view", comment: comment %>
        <% end %>
      </ul>
    </div>

    <% if current_user.friends_ids.include?(receiver.id) %>
      <div class="new-comment">
        <%= render "layouts/comment", post: post %>
      </div>
    <% end %>
  </div>
</div>